os: linux
dist: bionic

language: python
python:
  - 3.7

services:
  - docker  # required, but travis uses older version of docker :(

install:
  - docker --version  # document the version travis is using

stages:
  - test
  - docker_build
  - deploy

jobs:
  include:
    - stage: docker_build
      name: "build and push docker"
      script: |
        # LOGIN
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # BUILD
        docker build -t "$DOCKER_USERNAME"/minitwitimage:latest . -f Dockerfile-minitwit
        docker build -t "$DOCKER_USERNAME"/mysqlimage:latest . -f Dockerfile-mysql
        docker build -t "$DOCKER_USERNAME"/flagtoolimage:latest . -f Dockerfile-flagtool
        # PUSH
        docker push "$DOCKER_USERNAME"/minitwitimage:latest
        docker push "$DOCKER_USERNAME"/mysqlimage:latest
        docker push "$DOCKER_USERNAME"/flagtoolimage:latest

    - stage: test
      name: "run pytest"
      install: skip
      script: |
        docker build -t "$DOCKER_USERNAME"/minitwittestimage -f Dockerfile-minitwit-tests .
        yesÂ | docker-compose up -d
        docker run -it --rm --network=itu-minitwit-network "$DOCKER_USERNAME"/minitwittestimage

    - stage: deploy
      name: "deploy new version"
      install: skip
      # -o flag to get around "add ip to known hosts prompt"
      script: |
        ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER} "cd /vagrant && docker-compose pull && docker-compose up -d"
